# -*- coding: utf-8 -*-
"""world_population_barchart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XKMurfY7s1M5t53gIZgMbfoNKFbhBp_
"""

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Load the dataset
df = pd.read_csv("/content/world_population_data.csv")

# Keep only necessary columns
df = df[['country', '2023 population']]
df['2023 population'] = df['2023 population'].astype(int)  # Ensure population is integer

# Step 3: Top 10 countries by population
df_top10 = df.sort_values(by='2023 population', ascending=False).head(10)

# Step 4: Bar chart
plt.figure(figsize=(12, 7))
sns.set_style("whitegrid")
colors = sns.color_palette("viridis", len(df_top10))

plot = sns.barplot(x='country', y='2023 population', data=df_top10, palette=colors)

# Add labels
for i, val in enumerate(top10['2023 population']):
    plt.text(i, val + val * 0.02, f"{val:,}", ha='center', fontsize=10)

plt.title("Top 10 Most Populated Countries in 2023", fontsize=16)
plt.xlabel("Country")
plt.ylabel("Population (2023)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

# Save the bar chart
chart_filename = "population_barchart.png"
plt.savefig(chart_filename)

# Save the cleaned CSV
csv_filename = "cleaned_population_data.csv"
df_top10.to_csv(csv_filename, index=False)

# Download both files
files.download(chart_filename)
files.download(csv_filename)